# Generated by Django 3.1.4 on 2021-01-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('fake_room', 'Fake Room'), ('misleading', 'Misleading Description'), ('other', 'Other')], default='fake_room', max_length=20),
        ),
    ]
