# Generated by Django 3.1.4 on 2021-01-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=120)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=120, null=True)),
                ('phone_number', models.CharField(max_length=120)),
                ('user_status', models.CharField(choices=[('blocked', 'Blocked'), ('clear', 'Clear')], default='clear', max_length=20)),
            ],
        ),
    ]
